# Generated by Django 4.0.6 on 2022-07-18 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_alter_transacao_options_alter_transacao_observacoes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['dt_criacao']},
        ),
        migrations.AlterModelOptions(
            name='transacao',
            options={'ordering': ['categoria'], 'verbose_name_plural': 'Transações'},
        ),
    ]
